"""empty message

Revision ID: 4b6adc425fcb
Revises: b36b6500a418
Create Date: 2022-02-04 17:28:31.407605

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4b6adc425fcb'
down_revision = 'b36b6500a418'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requests', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.drop_column('requests', 'request_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requests', sa.Column('request_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('requests', 'created_at')
    # ### end Alembic commands ###
