"""empty message

Revision ID: 40daa82a42fa
Revises: efaaeb0d0a4b
Create Date: 2022-02-04 16:03:12.608011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40daa82a42fa'
down_revision = 'efaaeb0d0a4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('customers_credit_card_key', 'customers', type_='unique')
    op.drop_column('customers', 'credit_card')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('credit_card', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_unique_constraint('customers_credit_card_key', 'customers', ['credit_card'])
    # ### end Alembic commands ###
