"""empty message

Revision ID: 2b3fc4cb56ee
Revises: ef6cedad5ce5
Create Date: 2022-02-02 17:14:21.664805

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b3fc4cb56ee'
down_revision = 'ef6cedad5ce5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('requests',
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('equipment_id', sa.Integer(), nullable=False),
    sa.Column('request_location', sa.String(length=50), nullable=False),
    sa.Column('delivery_date', sa.String(length=10), nullable=False),
    sa.Column('request_time', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipments.id'], ),
    sa.PrimaryKeyConstraint('customer_id', 'equipment_id')
    )
    op.add_column('equipments', sa.Column('customer_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'equipments', 'customers', ['customer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'equipments', type_='foreignkey')
    op.drop_column('equipments', 'customer_id')
    op.drop_table('requests')
    # ### end Alembic commands ###
