"""empty message

Revision ID: efaaeb0d0a4b
Revises: adf3388a74ff
Create Date: 2022-02-04 15:46:47.922673

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'efaaeb0d0a4b'
down_revision = 'adf3388a74ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('requests')
    op.drop_column('customers', 'equipment_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('equipment_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_table('requests',
    sa.Column('customer_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('equipment_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('request_location', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('delivery_date', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('request_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name='requests_customer_id_fkey'),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipments.id'], name='requests_equipment_id_fkey'),
    sa.PrimaryKeyConstraint('customer_id', 'equipment_id', name='requests_pkey')
    )
    # ### end Alembic commands ###
