"""empty message

Revision ID: 137b8cd458e7
Revises: c8c8f19a9175
Create Date: 2022-02-02 17:39:00.367053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '137b8cd458e7'
down_revision = 'c8c8f19a9175'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('equipments_brand_name_key', 'equipments', type_='unique')
    op.drop_constraint('equipments_current_location_key', 'equipments', type_='unique')
    op.drop_constraint('equipments_daily_rate_key', 'equipments', type_='unique')
    op.drop_constraint('equipments_model_name_key', 'equipments', type_='unique')
    op.drop_constraint('equipments_year_key', 'equipments', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('equipments_year_key', 'equipments', ['year'])
    op.create_unique_constraint('equipments_model_name_key', 'equipments', ['model_name'])
    op.create_unique_constraint('equipments_daily_rate_key', 'equipments', ['daily_rate'])
    op.create_unique_constraint('equipments_current_location_key', 'equipments', ['current_location'])
    op.create_unique_constraint('equipments_brand_name_key', 'equipments', ['brand_name'])
    # ### end Alembic commands ###
