"""empty message

Revision ID: abee9328aadc
Revises: f9e64211ff33
Create Date: 2022-02-06 14:22:27.554183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abee9328aadc'
down_revision = 'f9e64211ff33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drivers', sa.Column('available', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('drivers', 'available')
    # ### end Alembic commands ###
