"""empty message

Revision ID: d95af0bfeb3e
Revises: 37127a4bbe97
Create Date: 2022-02-02 17:55:55.131169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd95af0bfeb3e'
down_revision = '37127a4bbe97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('customers_billing_address_key', 'customers', type_='unique')
    op.drop_constraint('customers_first_name_key', 'customers', type_='unique')
    op.drop_constraint('customers_last_name_key', 'customers', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('customers_last_name_key', 'customers', ['last_name'])
    op.create_unique_constraint('customers_first_name_key', 'customers', ['first_name'])
    op.create_unique_constraint('customers_billing_address_key', 'customers', ['billing_address'])
    # ### end Alembic commands ###
