"""empty message

Revision ID: c8c8f19a9175
Revises: 2b3fc4cb56ee
Create Date: 2022-02-02 17:27:36.928752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8c8f19a9175'
down_revision = '2b3fc4cb56ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('equipments_customer_id_fkey', 'equipments', type_='foreignkey')
    op.drop_column('equipments', 'customer_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('equipments', sa.Column('customer_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('equipments_customer_id_fkey', 'equipments', 'customers', ['customer_id'], ['id'])
    # ### end Alembic commands ###
