"""empty message

Revision ID: adf3388a74ff
Revises: d95af0bfeb3e
Create Date: 2022-02-04 11:58:51.555853

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'adf3388a74ff'
down_revision = 'd95af0bfeb3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('equipment_id', sa.Integer(), nullable=False))
    op.drop_column('requests', 'created_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requests', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('customers', 'equipment_id')
    # ### end Alembic commands ###
