"""empty message

Revision ID: 37127a4bbe97
Revises: 137b8cd458e7
Create Date: 2022-02-02 17:49:34.178547

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37127a4bbe97'
down_revision = '137b8cd458e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('equipments', 'year',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('equipments', 'brand_name',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('equipments', 'model_name',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('equipments', 'current_location',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('equipments', 'daily_rate',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('equipments', 'available',
               existing_type=sa.VARCHAR(length=5),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('equipments', 'available',
               existing_type=sa.VARCHAR(length=5),
               nullable=True)
    op.alter_column('equipments', 'daily_rate',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('equipments', 'current_location',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('equipments', 'model_name',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('equipments', 'brand_name',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('equipments', 'year',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
