"""empty message

Revision ID: 796afc07129f
Revises: abee9328aadc
Create Date: 2022-02-06 21:36:14.997767

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '796afc07129f'
down_revision = 'abee9328aadc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('requests',
    sa.Column('equipment_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('request_location', sa.String(length=50), nullable=False),
    sa.Column('delivery_date', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipments.id'], ),
    sa.PrimaryKeyConstraint('equipment_id', 'customer_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('requests')
    # ### end Alembic commands ###
