"""empty message

Revision ID: f9e64211ff33
Revises: 815250fe1fb0
Create Date: 2022-02-06 13:31:08.437285

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9e64211ff33'
down_revision = '815250fe1fb0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drivers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.String(length=20), nullable=False),
    sa.Column('last_name', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=20), nullable=False),
    sa.Column('contact_number', sa.String(length=10), nullable=False),
    sa.Column('drivers_license', sa.String(length=10), nullable=False),
    sa.Column('credit_card', sa.String(), nullable=False),
    sa.Column('billing_address', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contact_number'),
    sa.UniqueConstraint('credit_card'),
    sa.UniqueConstraint('drivers_license'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('drivers')
    # ### end Alembic commands ###
